services:
  - type: web
    name: tkd-transport
    env: python
    runtime: python
    buildCommand: |
      python --version
      pip --version
      pip install --upgrade pip
      pip install gunicorn
      pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.10.12
